### ISSUE TITLE
Review Guide to update references to Kaya Graphs; Carbon Intensity of Final Energy

### ISSUE THREAD

**Issue by travisfranck** [climateinteractive/enroads-guide#17]
One of the Kaya View graphs is being updated per https://github.com/climateinteractive/en-roads-app/issues/602.

Please review the RTD documentation to see if any references to Kaya need to be updated.  

The specific parameter being plotted did change.  Carbon Intensity of Primary Energy is being changed to Carbon Intensity of Final Energy  

Also, any screenshots/image may need updating.

Assigning to @llie to start.

**Comment by chrispcampbell** [comment]
@yasmeenzahar Since the app relies on the `enroads-guide` repo for the Kaya graphs description, I wanted to at least update the description so that it mentions "Final Energy" instead of "Primary Energy".  I found two relevant mentions, and I updated those in bddef56 so that they'll be included in the next release.  I'm leaving this open so that (once you're back) you can see if there are any other mentions or images that need updating.

**Comment by chrispcampbell** [comment]
@yasmeenzahar Can you see if there are any other references (besides the ones I fixed, see previous comment) that need updating in the guide?  I think this is the last thing in the guide repo for the September release, and then we can close out the milestone.  Thanks!

**Comment by yasmeenzahar** [comment]
Should be all set!

**Comment by chrispcampbell** [comment]
Yazzy fixed the remaining Kaya references in ae29b95 and 87418df.  Closing as "done".
