### ISSUE TITLE
Update Renewables 'Big Message' and 'Key Dynamics'?

### ISSUE THREAD

**Issue by yasmeenzahar** [climateinteractive/enroads-guide#28]
@llie @DrewJonesCI this is currently what we have for our Big Message and Key Dynamics in the Renewables section of the User Guide (also embedded in the Renwables slider of the app): 

**Big Message**
Subsidizing renewable energy is a helpful way to keep coal and gas in the ground and reduce future temperature. However, it isn’t a silver bullet; that is, it isn’t sufficient without other actions.

**Key Dynamics**
**Impact.** As you encourage renewables, watch Coal (brown line) and Natural Gas (blue line) both shift down in the “Global Sources of Primary Energy” graph. This shows the benefit of renewables for the climate – keeping coal, oil, and gas in the ground.
**Rebound effect.** Subsidies to renewables decrease energy costs, which increases energy demand over what it would have been otherwise (people use more energy when it is cheap). This rebound effect somewhat reduces the positive impact of encouraging renewable energy. View this dynamic with the graph “Final Energy Consumption.”
**Delays.** It takes time for the subsidies and encouragement of renewables to show up in installed capacity. Subsidies are phased in over 10 years so note in the “Renewable Final Energy Consumption” graph that the Current Scenario does not immediately differ from the Baseline.

Anything we want to edit/replace to better align with the new renewables trend?

**Comment by llie** [comment]
@DrewJonesCI @yasmeenzahar .How about this for the Renewables dynamics?... 

**Big Message**
Subsidizing renewable energy helps to limit coal and gas demand and reduce future temperature. Without other actions, however, it isn’t enough to keep fossil fuels in the ground.

**Key Dynamics**

**Impact.** As you encourage renewables, watch demand for Renewables (in green) grow and the demand for Coal (in brown) and Natural Gas (in blue) reduce in the “Global Sources of Primary Energy” graph. Renewable energy is already growing steadily in the baseline scenario so the additional subsidies help reduce emissions but only so much. 
**Rebound effect.** Additionally, subsidies to renewables decrease energy costs, which increase energy demand over what it would have been otherwise (people use more energy when it is cheap). This rebound effect somewhat reduces the positive impact of encouraging renewable energy. View this dynamic with the graph “Final Energy Consumption.”
**Delays.** It takes time for the subsidies and encouragement of renewables to show up in installed capacity. Subsidies are phased in over 10 years so note in the “Renewable Final Energy Consumption” graph that the Current Scenario does not immediately differ from the Baseline.

**Comment by yasmeenzahar** [comment]
Thanks E, looks good. Added to User Guide.
